#pragma config(Sensor, dgtl1,  right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left,           sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftPower = 99;
int rightPower = 78;
float wheelDiameter = 2.75;
float wheelCircumference = wheelDiameter * PI;
// float distance = 70;
// float numOfRotations = distance/wheelCircumference;
float turnRotations = 1.12;

void turnRight(int degrees) {
	float turnRotations = 1.12 / 90;
	SensorValue[left] = 0;
		SensorValue[right] = 0;
	while(SensorValue[left] < turnRotations * 360 * degrees) {
			motor[leftMotor] = leftPower;
			motor[rightMotor] = -rightPower;
			writeDebugStreamLine("Left: %d", SensorValue[left]);
			writeDebugStreamLine("Right: %d", SensorValue[right]);
	}
}

void turnLeft(int degrees) {
	float turnRotations = 1.12 / 90;
	SensorValue[left] = 0;
		SensorValue[right] = 0;
	while(SensorValue[left] < turnRotations * 360 * degrees) {
			motor[leftMotor] = -leftPower;
			motor[rightMotor] = rightPower;
			writeDebugStreamLine("Left: %d", SensorValue[left]);
			writeDebugStreamLine("Right: %d", SensorValue[right]);
	}
}

void travel(int distanceInInches) {
	motor[leftMotor] = leftPower;
	motor[rightMotor] = rightPower;
	SensorValue[left] = 0;
	SensorValue[right] = 0;
	float numOfRotations = distanceInInches/wheelCircumference;
		while(SensorValue[left] < numOfRotations * 360) {
			writeDebugStreamLine("Left: %d", SensorValue[left]);
			writeDebugStreamLine("Right: %d", SensorValue[right]);
		}
}

task main()
{
	SensorValue[left] = 0;
	SensorValue[right] = 0;
	travel(48);
	turnRight(150);
	travel(12);
	turnRight(150);
	travel(12);
	turnLeft(30);
	travel(30);
}
